### ISSUE TITLE
License mismatch between Cabal and LICENSE file

### ISSUE THREAD

**Issue by peti** [yesodweb/css-text#9]
The Cabal file says `BSD3`, but the `LICENSE` file actually contains a BSD3 license.

**Comment by MaxGabriel** [comment]
> The Cabal file says BSD3, but the LICENSE file actually contains a BSD3 license.

Did you mean to say something else?

**Comment by peti** [comment]
Ah, sorry! The Cabal file says `BSD3`, but the LICENSE file actually contains a BSD2 license.

**Comment by peti** [comment]
@snoyberg, ping?

**Comment by snoyberg** [comment]
Fixed in 76b2a547f9b1f258bb5c10d2f9a914d546f4d8fd
